### ISSUE TITLE
Adopt `graphql-ppx` 1.0

### ISSUE THREAD

**Issue by jfrolich** [FormidableLabs/reason-urql#219]
Are you looking to upgrade to `graphql-ppx` 1.0? It's a bit of a change but looking at the examples it allows to refactor the API to the following:

```reason
let request = GetPokemon.make(~name=pokemon, ());
let (Hooks.{response}, _) = Hooks.useQuery(~request, ());
```

into

```reason
let (response, _) = GetPokemon.use({name: pokemon});
```

Also you get all the other goodies like many bugfixes, better error messages, and - most importantly - records instead of objects.

You can extend queries/mutations/subscriptions, and this allows you to add the `use` function (see https://graphql-ppx.com) to create quite a nice and concise API surface. If you have any questions I am happy to help out!

**Comment by BlueHotDog** [comment]
Yes Please!! super looking forward to this!

**Comment by parkerziegler** [comment]
Hey @jfrolich! I'd definitely be interested in adopting it. If you'd like to start working on it, the contribution is more than welcome! I'll likely be swamped w/ work until this week, so that'd be the earliest I could get to it. But it's good to see that a community standard has emerged and yes, I'd be happy to officially move onto it 🎉

**Comment by jfrolich** [comment]
I don't use `reason-urql` but happy to answer questions!

**Comment by BlueHotDog** [comment]
I'm now giving it a try on a project. will see the exceptions i get and maybe i can help push this forward.

**Comment by parkerziegler** [comment]
Hey folks, I began working on this migration but have had a recent death in my family and won't be getting back to it for a few days (or, more likely, a week and a half). My first impressions:

- This looks like a great library! It does seem that it really encourages using functors as the main mechanism for accessing `query`, `parse`, etc. which are the main internals `reason-urql` cares about. However, many of our bindings and APIs as they stand aren't really setup for functors, and I've seen a healthy amount of reports from community members in the past that functors are a serious point of confusion for them. As it stands, I don't think we'd be able to easily adopt this library without a massive overhaul of our APIs, which I'm reticent to do.
- I do think there's a way around this, however (and maybe it's already possible and I'm just not quite getting it). I'd love to be able to access _everything_ off of `module type Operation` _without_ using functors, so that we have all internals of an `Operation` module available to our converter functions. In `graphql_ppx_re` this was available as the `Js.t` returned by calling `.make`, i.e.

```reason
let request = MyQuery.make();

let parse = request##parse;
let query = request##query;
let variables = request##variables;
```

This was _great_ because we didn't have to ship our own functors to consume `MyQuery`. If `graphql-ppx` could expose something like `definition` or `operation` that included these fields, it would make a great migration path for us. That would look something like:

```reason
Client.executeQuery(~request=MyQuery.operation, ());
```

`operation` would be a record with fields for everything from `module type Operation`.

If we do opt for the functor route, it would force us into make all hooks and `execute*` methods into functors, so we'd have code like this (pseudo-API):

```reason
open ReasonUrql;

module MyQuery = [%graphql {|
  query {
    dogs {
      name
      breed
      likes
    }
  }
|}];

module Executor = ExecuteQuery(MyQuery);

Executor.executeQuery(~var1, ~var2, /* additional options passed to the urql client */, ());
```

While this _might_ be feasible, I'm not actually sure this is a friendlier API. Let me know your thoughts when you get a minnute @jfrolich. Perhaps there is already a way to access everything off of `module type Operation` _without_ using a functor? If so, I'd love to know about it to push this forward. Thanks!

**Comment by jeddeloh** [comment]
The functor part is largely transparent to the end-user thanks to configuration in `bsconfig`. For your example, this could result in usage like:
```
module MyQuery = [%graphql {|
  query {
    dogs {
      name
      breed
      likes
    }
  }
|}];

MyQuery.useQuery(~var1, ~var2, ());
```

But it's not even necessary to use functors and the extension api. You can use first-class modules with normal functions. This is what reason-apollo-client does for client methods:
```
module MyQuery = [%graphql {|
  query {
    dogs {
      name
      breed
      likes
    }
  }
|}];

client.executeQuery(~query=(module MyQuery), {var1, var2})
```

Maybe look at `reason-apollo-client` for an example implementation? Happy to provide what context I can.

**Comment by jfrolich** [comment]
Sorry to hear about your family situation, @parkerziegler! Condolences! Be sure to take your time off.

To respond to your questions. Like @jeddeloh said the functor is just used because it's the most feasible way to more deeply integrate with the `ppx`. It's transparent to the user (it just adds extra functions or values to the query/mutation/fragment module behind the scenes).

In the current `urql` API, it makes use of the old `make` function on the query module. Returning both the variable object and it also the query string itself. 

In the new situation we can extend the query to have a `make` or `use` function and it can do anything within that function, and access all module values or functions. If you want to pass in variables you can just pass in the record of variables `Query.t_variables` (no labeled arguments to a function necessary anymore). 

If you have a lot of optional variables you can still "make" this object with the `makeVariables` constructor function (it has optional arguments so you don't have to provide the optional arguments explicitly).

Regarding your point of having a `definition` (that was what we had before) field on the query itself. There was actually quite a lot of [discussion](https://github.com/reasonml-community/graphql-ppx/issues/133) on this front. And if you want something like this, you can just pass the whole module as @jeddeloh explained above. This is more elegant in the produced code, and it's also more powerful (you can access anything on the query module that is generated by `graphql-ppx`. The syntax to this will improve in the future. I personally think that just a `use` function on the Query module itself is much nicer from an API perspective to the user.

**Comment by amiralies** [comment]
@parkerziegler are you working on this? I can help to adopt faster

**Comment by parkerziegler** [comment]
👋 Hey @amiralies, I'd love the help! We're fairly clear on the API we're targeting, I just haven't had any time to work on this recently due to some personal stuff and aggressive deadlines in my day job 😅 

We're hoping to keep the API _fairly_ similar to v2 by using [first-class modules](https://dev.realworldocaml.org/first-class-modules.html). This would mean that our hooks APIs would look something like this:

```reason
module MyQuery = [%graphql {|
  query {
    dogs {
      name
      breead
      likes
    }
  }
|}];

[@react.component]
let make = () => {
  let ({ response }, executeQuery) =
    Hooks.useQuery(~query=(module MyQuery), ~variables=MyQuery.makeVariables(), ());

  switch (response) {
    | Data(d) => /* UI */
    | Error(e) => /* Error UI */
    // Other variant tags on response
  }
};
```

Let me know if that makes sense! We have a very similar pattern in `Client.executeQuery`, `Client.executeMutation`, and `Client.executeSubscription`, so you can look there for more clarity. You should look at the `v3` branch to find those APIs, and any PRs should be made directly into that branch. Thanks for the assistance!

**Comment by amiralies** [comment]
I actually like the API with FCM. It aligns well with urql's api and there's no need for additional config in `bsconfig.json` (although it's very simple), but we should consider FCM is an advanced language feature.
I will play around this API do some experiment.

**Comment by jfrolich** [comment]
@parkerziegler, you could consider having the variables as the only positional argument. In case when there are no variables the type of `t_variables` is unit, so you can just call the function without the last argument.

**Comment by BlueHotDog** [comment]
Hi guys, just checking in, how stable is the v3 branch? can we give it a whirl on a real project?

**Comment by amiralies** [comment]
hooks are not converted to new api yet, I'll send a PR in next week.

**Comment by BlueHotDog** [comment]
Thanks,
Maybe its worth while to add a tracker to see what's left to be done? maybe others will pitch in?

**Comment by amiralies** [comment]
You're right, I'll do that in a WIP PR.

**Comment by parkerziegler** [comment]
@BlueHotDog `v3` branch is stable-ish. If you use it, be aware of the following:

- `Client.execute*` and `Client` methods generally are using `@reasonml-community/graphql-ppx`. There may be some changes to those APIs before `v3` is released, but if so they'll be fairly minor to what's currently on `v3`.
- `urql` is now a `peerDependency` of the library, along with its `peerDependencies`. So the full install will entail:

```sh
yarn add reason-urql urql graphql reason-react react @reasonml-community/graphql-ppx
```

for a complete, from scratch install. The examples on `v3` have been updated and are a good reference.
- Hooks are still using `@baransu/graphql_ppx_re`. @amiralies is updating this currently, and I'll review their PR when its ready. It's a bit tricky getting first-class modules working, so there may be a few PRs entailed to arrive at an API we really like.

**Ways Folks Can Help**

PRs updating the docs to reflect the new APIs, especially for `Client.execute*` methods would be amazing. There'll be lots of docs work generally before `v3` can be released, so any work we put in now will help accelerate later.

In general, maintenance for this project is a bit challenging for me – I don't get time at work to contribute to it, so everything I'm doing (like most OSS maintainers) is evenings and weekends. I know folks are anxious for this feature – I just honestly haven't had the time to devote to it recently. Moreover, I want to make sure `v3` is really buttoned up such that, when we do release it, folks have a smooth upgrade path. Thanks for being so willing to test early release candidates and searching for proactive ways to help ❤️

**Comment by BlueHotDog** [comment]
@parkerziegler you're doing a stellar job! we'll try to help. we'll wait until hooks are done and start testing it and filling in gaps.
Thank you so much for providing visibility

**Comment by amiralies** [comment]
@BlueHotDog I've pushed some changes into my branch. you can give it a try if you want!

**Comment by parkerziegler** [comment]
This work has been merged into the `v3` branch. I'm finishing up final release notes for `v3.0.0-rc.0` and will publish that later today. Thanks for the work here everyone!

**Comment by jfrolich** [comment]
Amazing work @parkerziegler!
