### ISSUE TITLE
useDynamicMutation hook: Getting an error for returned executeMutation function with no variables

### ISSUE THREAD

**Issue by saracodes** [FormidableLabs/reason-urql#228]
Hi! Thanks for the fantastic work 👏🏽 
I found a bug, which turned out not to be so critical, but it might be useful to others to resolve it or be aware of it.

When I use the `useDynamicMutation` hook with no variable for the returned executeMutation function, I get an error: `This argument cannot be applied without label`.
In this case, it is possible to use `useMutation`, and that’s what I did eventually.
But with the `useDynamicMutation` used before there was no way to make it works.

getting an error:
```reason
let ({fetching, response}, executeCreateStoryline) =
    ReasonUrql.Hooks.useDynamicMutation(CreateStoryline.definition);
  let createStoryline = () => {
    let _: Js.Promise.t(ReasonUrql.Types.operationResult) = executeCreateStoryline(); // error: This argument cannot be applied without label
    ();
  };
```

works well:
```reason
let ({fetching, response}, executeCreateStoryline) =
    ReasonUrql.Hooks.useMutation(~request=CreateStoryline.make());
  let createStoryline = () => {
    let _: Js.Promise.t(ReasonUrql.Types.operationResult) = executeCreateStoryline();
    ();
  };
```

**Comment by parkerziegler** [comment]
Huh, this is an interesting one and I'm not totally sure what's happening here! Does it give you a specific labelled parameter that it's expecting, or just "label"?

A good thing to note — we're going to be releasing `v3.0.0` very soon (likely this weekend), which removes `useDynamicMutation` altogether. `useMutation` will function as `useDynamicMutation` does currently, where variables are applied at execution time — this brings it more inline with how `urql` works while still preserving the type safety on variables and responses from your GraphQL API.

So, for now, I don't think there's much to do on this end. Especially with standard `useMutation` as a workaround. I would bet that it may be related to the upstream PPX and how we integrate with the GraphQL query module internals, but since we're moving off of that PPX imminently I don't see too much point in investigating. If we find that similar behavior arises after v3 is released, let's reopen and dive in more. Thanks for using the library and for finding this!

**Comment by saracodes** [comment]
v3.0.0 🥳
great news!
I will test the code again with the new version and update if it reoccurs.
just for the record, if anyone will need some more details later on - 
it didn't expect any specific label, it was just the general error of: `This argument cannot be applied without label`. and it didn't help to pass some of the optional `executeMutation` arguments like requestPolicy etc.

Thank you for the detailed reply!
