### ISSUE TITLE
Two questions related to testing

### ISSUE THREAD

**Issue by BlueHotDog** [FormidableLabs/reason-urql#252]
Hi, trying to figure out how to do this:
https://formidable.com/open-source/urql/docs/advanced/testing/
And (probably less related to this lib, but still) this:
https://storybook.js.org/addons/@urql/storybook-addon

Couldn't find any info(i'm using v2.1.0). 
Any clues? 
The only option i see now is mocking fetch using jest-mock-fetch.. but just wanted to make sure i'm approaching this correctly.

**Comment by BlueHotDog** [comment]
Ok, answered the second one myself. for anyone reaching this later:
https://github.com/draftbit/bs-storybook now supports CSF, which supports passing params. so this works:
```
component->CSF.addMeta(
  ~name="Name of comp",
  ~parameters={
    "urql": () =>
      {
        "data": {
          "query_name": data,
        },
      },
  },
  (),
)
```

Still can't figure out the best approach to mock reason-urql though

**Comment by parkerziegler** [comment]
Hey @BlueHotDog! Interesting questions, and ones I haven't actually considered before. Let's start with the testing piece.

So, the type of the `urql` Client _instance_, `t`, is abstract. For this reason, I think it'll be difficult to follow exactly what the `urql` docs present, because we can't just mock `executeQuery`, `executeMutation`, etc. in a record and hand it to `Provider` — it needs to be of type `Client.t`.

To start out, I would try creating a client and mocking its methods with `%%raw`, calling `jest.spyOn(client, 'executeQuery').mockImplementation(() => never)` (or however you want to mock this). For example:

```rescript
it("mocks the Client", () => {
  let client = Client.make(~url="https://localhost:3000", ())
  let never = Wonka.never

  %%raw(`
    jest.spyOn(client, 'executeQuery').mockImplementation(() => never);
    jest.spyOn(client, 'executeMutation').mockImplementation(() => never);
  `)
  
  // Mounting your component and asserting here.
})
```

In terms of asserting on the mock calls methods themselves, `bs-jest` unfortunately doesn't seem to have matchers for `toBeCalled`, and even [the `MockJs` module is experimental](https://github.com/glennsl/bs-jest/blob/6b740c424222fbe800d11ffbaa930b206b927a0a/src/jest.mli#L154). So, I'd recommend forcing states as recommended in the `urql` docs and asserting on component output rather than mock calls.

I know it's not a super satisfying solution, but hopefully a useful starting point!

**Comment by BlueHotDog** [comment]
Thanks @parkerziegler 
I'm very happy of writing my own bindings(god knows that's a prerequisite using rescript :) ). Just wanted to see if i missed something before rolling my own.
Also, maybe we can add a MockContext component that'll accept such arguments?

**Comment by parkerziegler** [comment]
@BlueHotDog Yep, that's definitely a solid idea. Something to the effect of:

```rescript
type mockClient = {
  executeQuery: MockJs.fn,
}

@module("urql") @react.component
external make: (~value: mockClient, ~children: React.element) => React.element = "Provider"
```

**Comment by parkerziegler** [comment]
Going to close this for now, but feel free to reopen if there's more that isn't working here or if this seems unachievable in user-land and we can chat further. Thanks!
