### ISSUE TITLE
[Proposal] Adopt redoc for documentation

### ISSUE THREAD

**Issue by gugahoa** [FormidableLabs/reason-urql#65]
Hello, everyone!
There's this great tool called [redoc](https://jaredforsyth.com/redoc/) that could benefit the project. 
It generates a good looking documentation website using implementation files and docblocks.

I see two main benefits in adopting it:
- Nice searchable documentation to refer to future users
- Increase the amount of documentation inside the code for future contributors

What's everyone's opinion?

**Comment by parkerziegler** [comment]
👋Hey @gugahoa Good suggestion! My only hesitation about this is that Formidable has its own sets of doc landers that are revamped for each project (see the `urql` docs site [here](https://formidable.com/open-source/urql/docs/)). I think in the short term we'll probably stick with just Markdown. Once we get `v1` out, I'll start working on the formal docs site for `reason-urql`, which will fit in this style. It's a newer thing we're doing to keep our docs across Formidable looking consistent, but since this project is still in experimental status it hasn't yet gotten much focus from the design team.

**Comment by gugahoa** [comment]
I think it wouldn't hurt to have redoc and later change it to something else, since it uses in-code documentation to create the pages. No work would be thrown out of the window this way, I think it's a win-win scenario even in the long-term where redoc is replaced by Formidable own doc site.

**Comment by parkerziegler** [comment]
That makes sense! Would you be interested in working to get it integrated? I'm a bit swamped helping with `urql` v1.1 and on client work, but I agree that redoc would be helpful in the iterim as Formidable decides on whether we want a formal docs site for this project 👍

**Comment by gugahoa** [comment]
Sure, I already started a local branch to test out redoc before creating the issue. 

Before making a PR with redoc, I plan to simply make a PR with docblock for some modules and after having code doc inplace I'll make a PR adding redoc. How does that sound to you?

**Comment by parkerziegler** [comment]
Sounds good!

**Comment by gugahoa** [comment]
I ended up not touching this, after looking into it a little better, redoc doesn't provide features I consider essential. What would be the thoughts on using [Docusaurus v2](https://v2.docusaurus.io/)? It can be seen in action in the [reason-relay docs](https://reason-relay-documentation.zth.now.sh/docs/start-here) and looks quite powerful

**Comment by parkerziegler** [comment]
Closing for now — I don't think we have any plans for a formal docs site for this project until it reaches higher popularity. When that time comes it'll likely get folded into the `urql` documentation or a similarly-styled site on the Formidable domain.
